CREATE TABLE `board_category` (
`category_id` BIGINT NOT NULL AUTO_INCREMENT,
`name_kr` VARCHAR(45) NULL,
`name_en` VARCHAR(45) NULL,
`create_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
`update_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`category_id`));
